//! BetterDesk Desktop native core.
//!
//! The crate owns configuration validation, interoperability framing and
//! transport/session primitives. The Flutter application talks to this core
//! through the small exported ABI in addition to the higher-level bridge
//! generated by the desktop build.

#[allow(clippy::all)]
pub mod hbb {
    include!(concat!(env!("OUT_DIR"), "/hbb.rs"));
}

pub mod audio;
pub mod cdap;
pub mod cdap_desktop;
pub mod clipboard;
pub mod config;
pub mod crypto;
pub mod desktop;
pub mod desktop_session;
pub mod file_transfer;
pub mod frame;
pub mod helper;
pub mod identity;
pub mod registration;
pub mod rustdesk;
pub mod rustdesk_session;
pub mod security;
pub mod session;
pub mod transport;
pub mod windows_media;

pub const PRODUCT_VERSION: &str = env!("CARGO_PKG_VERSION");

#[no_mangle]
pub extern "C" fn bd_client_version() -> *const std::ffi::c_char {
    static VERSION: &[u8] = b"BetterDesk Desktop\0";
    VERSION.as_ptr().cast()
}

/// Validate a UTF-8 server URL from a C/Flutter FFI caller.
///
/// The pointer is borrowed for the duration of this call and is never stored.
///
/// # Safety
///
/// `value` must be either null or a valid, NUL-terminated pointer to a
/// UTF-8-compatible C string that remains readable for the duration of this
/// call.
#[no_mangle]
pub unsafe extern "C" fn bd_validate_server_url(value: *const std::ffi::c_char) -> u8 {
    if value.is_null() {
        return 0;
    }
    let Ok(value) = std::ffi::CStr::from_ptr(value).to_str() else {
        return 0;
    };
    u8::from(config::validate_panel_url(value).is_ok())
}

/// Request UAC/polkit authorization for one allowlisted machine operation.
///
/// # Safety
///
/// `operation` must be either null or a valid, NUL-terminated UTF-8 string
/// that remains readable for the duration of this call.
#[no_mangle]
pub unsafe extern "C" fn bd_request_admin(operation: *const std::ffi::c_char) -> u8 {
    if operation.is_null() {
        return 0;
    }
    let Ok(operation) = std::ffi::CStr::from_ptr(operation).to_str() else {
        return 0;
    };
    let operation = match operation {
        "change_server_endpoint" => security::PrivilegedOperation::ChangeServerEndpoint,
        "change_server_key" => security::PrivilegedOperation::ChangeServerKey,
        "configure_unattended_access" => security::PrivilegedOperation::ConfigureUnattendedAccess,
        "configure_autostart" => security::PrivilegedOperation::ConfigureAutostart,
        "configure_service" => security::PrivilegedOperation::ConfigureService,
        "configure_system_proxy" => security::PrivilegedOperation::ConfigureSystemProxy,
        "install_update" => security::PrivilegedOperation::InstallUpdate,
        _ => return 0,
    };
    u8::from(helper::request_authorization(operation).is_ok())
}

fn ffi_string(
    slot: &'static std::sync::OnceLock<std::sync::Mutex<std::ffi::CString>>,
    value: String,
) -> *const std::ffi::c_char {
    let storage = slot.get_or_init(|| {
        std::sync::Mutex::new(std::ffi::CString::new(String::new()).expect("empty CString"))
    });
    let mut current = storage.lock().expect("identity FFI mutex poisoned");
    *current = std::ffi::CString::new(value).expect("generated identity is NUL-free");
    current.as_ptr()
}

#[no_mangle]
pub extern "C" fn bd_generate_device_id() -> *const std::ffi::c_char {
    static DEVICE_ID: std::sync::OnceLock<std::sync::Mutex<std::ffi::CString>> =
        std::sync::OnceLock::new();
    let value = identity::generate_device_id().unwrap_or_else(|_| "000000000".to_owned());
    ffi_string(&DEVICE_ID, value)
}

#[no_mangle]
pub extern "C" fn bd_generate_rotating_password() -> *const std::ffi::c_char {
    static PASSWORD: std::sync::OnceLock<std::sync::Mutex<std::ffi::CString>> =
        std::sync::OnceLock::new();
    let value = identity::generate_rotating_password()
        .unwrap_or_else(|_| "BetterDesk-identity-unavailable".to_owned());
    ffi_string(&PASSWORD, value)
}

#[no_mangle]
pub extern "C" fn bd_generate_identity_keypair() -> *const std::ffi::c_char {
    static KEYPAIR: std::sync::OnceLock<std::sync::Mutex<std::ffi::CString>> =
        std::sync::OnceLock::new();
    let value =
        identity::generate_keypair().unwrap_or_else(|_| r#"{"private":"","public":""}"#.to_owned());
    ffi_string(&KEYPAIR, value)
}

/// Capture one bounded JPEG frame into a caller-owned buffer.
///
/// Returns the number of bytes written, or `-1` when capture fails or the
/// output buffer is too small.
///
/// # Safety
///
/// `output` must point to at least `capacity` writable bytes, unless
/// `capacity` is zero.
#[no_mangle]
pub unsafe extern "C" fn bd_capture_screen_jpeg(output: *mut u8, capacity: usize) -> isize {
    let Ok(frame) = windows_media::capture_primary_jpeg(75) else {
        return -1;
    };
    if output.is_null() || frame.data.len() > capacity {
        return -1;
    }
    std::ptr::copy_nonoverlapping(frame.data.as_ptr(), output, frame.data.len());
    frame.data.len() as isize
}

/// Apply one JSON-encoded desktop input event on Windows.
///
/// # Safety
///
/// `value` must be null or a valid NUL-terminated UTF-8 string readable for
/// the duration of this call.
#[no_mangle]
pub unsafe extern "C" fn bd_inject_input(value: *const std::ffi::c_char) -> u8 {
    if value.is_null() {
        return 0;
    }
    let Ok(value) = std::ffi::CStr::from_ptr(value).to_str() else {
        return 0;
    };
    let Ok(input) = serde_json::from_str::<desktop::DesktopInput>(value) else {
        return 0;
    };
    u8::from(windows_media::inject_input(&input).is_ok())
}

/// Start the asynchronous RustDesk-compatible RegisterPk lifecycle.
///
/// The JSON configuration contains only public connection fields. The public
/// identity key is decoded and sent to the signal server; the private key
/// never crosses this ABI.
#[no_mangle]
pub unsafe extern "C" fn bd_start_registration(
    config_json: *const std::ffi::c_char,
    device_id: *const std::ffi::c_char,
    public_key: *const std::ffi::c_char,
) -> u8 {
    if config_json.is_null() || device_id.is_null() || public_key.is_null() {
        return 0;
    }
    let (Ok(config_json), Ok(device_id), Ok(public_key)) = (
        std::ffi::CStr::from_ptr(config_json).to_str(),
        std::ffi::CStr::from_ptr(device_id).to_str(),
        std::ffi::CStr::from_ptr(public_key).to_str(),
    ) else {
        return 0;
    };
    u8::from(registration::start(config_json, device_id, public_key))
}

#[no_mangle]
pub extern "C" fn bd_registration_status() -> *const std::ffi::c_char {
    static REGISTRATION_STATUS: std::sync::OnceLock<std::sync::Mutex<std::ffi::CString>> =
        std::sync::OnceLock::new();
    ffi_string(&REGISTRATION_STATUS, registration::status())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ffi_version_is_nul_terminated() {
        let ptr = bd_client_version();
        let version = unsafe { std::ffi::CStr::from_ptr(ptr) };
        assert_eq!(version.to_str().unwrap(), "BetterDesk Desktop");
    }
}
